name: Development Deployment

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_NON_PROD }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_NON_PROD }}

jobs:
  deploy-staging:
    name: Staging Deployment
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2
        with:
          clean: true
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Preparing branch
        run: echo running on branch ${GITHUB_SHA}

      - name: Install dependencies
        run: pnpm ci

      - name: Build
        run: pnpm run buildUi

      - name: Deploy to development
        uses: reggionick/s3-deploy@v3
        with:
          folder: libs/copilot/dist
          bucket: tinvio-copilot-development
          bucket-region: ap-southeast-1
          dist-id: E109CEHCKN8OF9  
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true